obj-m += kernel_first.o
all:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) modules
clean:
	make -C /lib/modules/$(shell uname -r)/build M=$(PWD) clean
test:
	sudo dmesg -C
	sudo insmod kernel_first.ko
	sudo rmmod kernel_first.ko
	dmesg